April Tag Vision
iron-claw-972/FRC-2024 pull request #15
Opened 2023-12-14 00:14 UTC by Kyle-Eldridge

## Overview

This PR will add April tag vision and grid alignment. It will update the pose using April tags, and it will use that pose combined with the robot odometry and PathPlanner to align to the grid, single substation, and both parts of the double substation..

## Design Doc

Vision documentation:
https://docs.google.com/document/d/13oBUrnHFNT4qX8u-soSRpcp3eSanAqlw8NOVhKwLHtQ/edit#heading=h.fmb594l3t3dt

## Tests Ran

I aligned to the grid and it worked. I also measured the position it thought it was at, and it was within 0.5 inches of where the robot actually was on one of my tests. We might have to update the scale factor next year, but 0.9 works this year (I don't know why, but it works).

## Additional Notes

Use the DPad to select the grid location to align to. Select grid, column in the grid, and row. Use the left button on the DPad to select the left grid/column, the up button to select the middle one, and the right button to select the right one. The row isn't used; just click any of the 3 buttons. Press down to clear the previous selection if you press a wrong button. Hold RB to align to the selected grid node, LB to align to the single substation, Y to align to the part of the double substation closer to the wall, and B to align to the part of the double substation closest to the opponent's community.

2023-12-19 21:55 UTC, Kyle-Eldridge commented
@Pennedrose @omegaladon @Ash1R 
This PR is finished. I merged it with working-drivetrain-code, so it has the most recent drivetrain code. Everything is added and it compiled (after fixing >150 errors).

2024-01-12 03:34 UTC, Pennedrose commented on .github/CODEOWNERS
can u change this to @Pennedrose @Kyle-Eldridge and @chem7397

2024-01-12 03:37 UTC, Pennedrose commented on src/main/java/frc/robot/RobotContainer.java
for the drivetraintabs, there should be a space between the lambda expression and drive.getModules. simple formatting thing. why are you deleting test commands for shuffleboard here?

2024-01-12 03:37 UTC, Pennedrose commented on src/main/java/frc/robot/commands/DefaultDriveCommand.java
why change blue to red on line 45

2024-01-12 03:38 UTC, Pennedrose commented on src/main/java/frc/robot/commands/GoToPose.java
does this and the next file work?

2024-01-12 03:39 UTC, Pennedrose commented on src/main/java/frc/robot/commands/auto_comm/PathPlannerCommand.java
have u tested this

2024-01-12 03:40 UTC, Pennedrose commented on src/main/java/frc/robot/commands/test_comm/PoseTransformTest.java
why commenting some stuff out?

2024-01-12 03:41 UTC, Pennedrose commented on src/main/java/frc/robot/commands/vision/AimAtTag.java
really nice, very clean

2024-01-12 03:47 UTC, Pennedrose commented on src/main/java/frc/robot/commands/vision/TestVisionDistance.java
great overall, some typos on line 67 lol. why is there an option to use this test with different speeds? should it not just be the same speed every time when running this test

2024-01-12 03:47 UTC, Pennedrose commented on src/main/java/frc/robot/constants/Constants.java
will change this back to GlobalConstants as per standardization in later code cleanup pull request, but this is fine for now.

2024-01-12 03:48 UTC, Pennedrose commented on src/main/java/frc/robot/constants/miscConstants/FieldConstants.java
have these all been added? is line 16 unneccessary

2024-01-12 03:52 UTC, Pennedrose commented on src/main/java/frc/robot/subsystems/Drivetrain.java
assuming the following changes were made in drivetrain pull request

2024-01-12 03:59 UTC, Pennedrose commented on src/test/java/frc/robot/constants/AprilTagPoseTest.java
maybe this should have a greater tolerance than 0.0001, historically april tags are not in the same location every time between matches that accurately. for example, last year at a regional there were two inches off. something to consider

2024-01-12 03:59 UTC, Pennedrose commented on src/test/java/frc/robot/constants/ConstantsTest.java
why commenting this out?

2024-01-12 04:00 UTC, Pennedrose requested changes
Overall very good, some minor things that I believe should be changed.

2024-01-12 15:52 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/commands/DefaultDriveCommand.java
Controls should be inverted for red, not blue. The controls were inverted in the simulator.

2024-01-12 15:58 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/RobotContainer.java
If you're talking about the last few lines in the constructor for RobotContainer, I think those were deleted when merging with Working-Drivetrain-Code. The functions mentioned there don't exist anymore.

2024-01-12 16:01 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/commands/GoToPose.java
The last time I tested it, it worked. That was what I used for grid alignment. I think it says in a comment somewhere (maybe in another command) that the PID constants don't let the command finish, but the command itself works.

2024-01-12 16:04 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/commands/auto_comm/PathPlannerCommand.java
Again, this was  used and tested in grid alignment. Also, I think this is mostly unchanged since last year.

2024-01-12 18:49 UTC, Kyle-Eldridge commented on src/test/java/frc/robot/constants/AprilTagPoseTest.java
This is to test the constants and the field layout from vision, not the real positions. These 2 things should be exactly the same.

2024-01-12 18:50 UTC, Kyle-Eldridge commented on src/test/java/frc/robot/constants/ConstantsTest.java
I think this is from the drivetrain code.

2024-01-12 18:50 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/subsystems/Drivetrain.java
Except for the odometry, yes.

2024-01-13 00:58 UTC, Kyle-Eldridge commented on src/main/java/frc/robot/commands/vision/TestVisionDistance.java
The different speeds also allow it to run in different directions (negative speed). If there has to be a parameter to control direction, it's easier to use the same parameter to control speed instead of just direction. I also fixed the typo.

2024-01-13 04:10 UTC, Pennedrose commented on src/main/java/frc/robot/commands/vision/TestVisionDistance.java
Makes sense! Thank you!

2024-01-13 04:11 UTC, Pennedrose commented on src/main/java/frc/robot/commands/vision/TestVisionDistance.java
Also, I still see the typos (i know super nit picky)

2024-01-13 04:18 UTC, Pennedrose commented on src/main/java/frc/robot/commands/DefaultDriveCommand.java
Sounds good!

2024-01-13 04:18 UTC, Pennedrose commented on src/main/java/frc/robot/commands/GoToPose.java
Fantastic!

2024-01-13 04:21 UTC, Pennedrose approved these changes

2024-01-13 04:21 UTC, Pennedrose commented
im getting a check failure that it is not building

2024-01-13 05:40 UTC, Ash1R approved these changes

2024-01-13 18:10 UTC, Kyle-Eldridge commented
It builds on VS Code, but it doesn't build on GitHub for some reason. (something about PathPlanner)

2024-01-13 18:58 UTC, merged